### ISSUE TITLE
Certificate issue on the online book

### ISSUE THREAD

**Issue by cderv** [pablo14/data-science-live-book#17] opened 2021-07-08 08:16 UTC
Hi, 

Just to warn you that it seems there is a certificate issue for HTTPS link to the book. 

![image](https://user-images.githubusercontent.com/6791940/124887478-7f32dd00-dfd5-11eb-9486-0575a099ff25.png)

Seems like the certificate expired on 05/07/2021

**Comment by jmcastagnetto** [comment] 2024-04-14 17:27
As of 2024-04-14, I cannot reproduce this issue (Firefox, Chromium, and Chrome running on Ubuntu Linux 22.04LTS). It might have been fixed on the Github hosting side.

**Closed as completed** 2024-04-29 08:27 UTC
